// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3SsBExK-NJHTsh9GmWcvpXtKDbTYs5jk',
    appId: '1:343705544018:web:3a4d15924b08e2e444868b',
    messagingSenderId: '343705544018',
    projectId: 'health-85d49',
    authDomain: 'health-85d49.firebaseapp.com',
    storageBucket: 'health-85d49.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLVR3V0ruGzLcvonn79-jgcVVWgrIItL0',
    appId: '1:343705544018:android:e5115a3b4158e04344868b',
    messagingSenderId: '343705544018',
    projectId: 'health-85d49',
    storageBucket: 'health-85d49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCJm8Ctxuvmx0Q2gPDezX6g-JCgBwwU6Y',
    appId: '1:343705544018:ios:2b27149e031f4d6f44868b',
    messagingSenderId: '343705544018',
    projectId: 'health-85d49',
    storageBucket: 'health-85d49.appspot.com',
    iosClientId: '343705544018-92k24n23bj1asg63tm3mhnmceoadoauj.apps.googleusercontent.com',
    iosBundleId: 'com.example.hareesNewProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCJm8Ctxuvmx0Q2gPDezX6g-JCgBwwU6Y',
    appId: '1:343705544018:ios:491f04624ec3045144868b',
    messagingSenderId: '343705544018',
    projectId: 'health-85d49',
    storageBucket: 'health-85d49.appspot.com',
    iosClientId: '343705544018-p9q83gog6ehsjtsm2pbnva49065dho50.apps.googleusercontent.com',
    iosBundleId: 'com.example.hareesNewProject.RunnerTests',
  );
}
